from builder.builder import *

def generate_block_elements(gs: GlyphSet):
	def generate_quadrant(glyph, q1, q2, q3, q4):
		if q1:
			glyph.data[0:int(glyph.height / 2), 0:int(glyph.width / 2)].fill(True)
		if q2:
			glyph.data[0:int(glyph.height / 2), int(glyph.width / 2):glyph.width].fill(True)
		if q3:
			glyph.data[int(glyph.height / 2):glyph.height, 0:int(glyph.width / 2)].fill(True)
		if q4:
			glyph.data[int(glyph.height / 2):glyph.height, int(glyph.width / 2):glyph.width].fill(True)

	def generate_sextant(glyph, q1, q2, q3, q4, q5, q6):
		if q1:
			glyph.data[0:int(glyph.height / 3), 0:int(glyph.width / 2)].fill(True)
		if q2:
			glyph.data[0:int(glyph.height / 3), int(glyph.width / 2):glyph.width].fill(True)
		if q3:
			glyph.data[int(glyph.height / 3):int(glyph.height * 2 / 3), 0:int(glyph.width / 2)].fill(True)
		if q4:
			glyph.data[int(glyph.height / 3):int(glyph.height * 2 / 3), int(glyph.width / 2):glyph.width].fill(True)
		if q5:
			glyph.data[int(glyph.height * 2 / 3):glyph.height, 0:int(glyph.width / 2)].fill(True)
		if q6:
			glyph.data[int(glyph.height * 2 / 3):glyph.height, int(glyph.width / 2):glyph.width].fill(True)

	gs.create(0x2580, lambda glyph: glyph.data[0:int(glyph.height / 2), 0:glyph.width].fill(True))
	for i in range(8):
		gs.create(0x2581 + i, lambda glyph: glyph.data[min(glyph.height - 1, int(glyph.height * (7 - i) / 8)):glyph.height, 0:glyph.width].fill(True))
	for i in range(7):
		gs.create(0x2589 + i, lambda glyph: glyph.data[0:glyph.height, 0:max(1, int(glyph.width * (7 - i) / 8))].fill(True))
	gs.create(0x2590, lambda glyph: glyph.data[0:glyph.height, int(glyph.width / 2):glyph.width].fill(True))
	gs.create(0x2594, lambda glyph: glyph.data[0:max(1, int(glyph.height / 8)), 0:glyph.width].fill(True))
	gs.create(0x2595, lambda glyph: glyph.data[0:glyph.height, min(glyph.width - 1, int(glyph.width * 7 / 8)):glyph.width].fill(True))
	gs.create(0x2596, lambda glyph: generate_quadrant(glyph, False, False, True, False))
	gs.create(0x2597, lambda glyph: generate_quadrant(glyph, False, False, False, True))
	gs.create(0x2598, lambda glyph: generate_quadrant(glyph, True, False, False, False))
	gs.create(0x2599, lambda glyph: generate_quadrant(glyph, True, False, True, True))
	gs.create(0x259A, lambda glyph: generate_quadrant(glyph, True, False, False, True))
	gs.create(0x259B, lambda glyph: generate_quadrant(glyph, True, True, True, False))
	gs.create(0x259C, lambda glyph: generate_quadrant(glyph, True, True, False, True))
	gs.create(0x259D, lambda glyph: generate_quadrant(glyph, False, True, False, False))
	gs.create(0x259E, lambda glyph: generate_quadrant(glyph, False, True, True, False))
	gs.create(0x259F, lambda glyph: generate_quadrant(glyph, False, True, True, True))

	gs.create(0x1FB00, lambda glyph: generate_sextant(glyph, True, False, False, False, False, False))
	gs.create(0x1FB01, lambda glyph: generate_sextant(glyph, False, True, False, False, False, False))
	gs.create(0x1FB02, lambda glyph: generate_sextant(glyph, True, True, False, False, False, False))
	gs.create(0x1FB03, lambda glyph: generate_sextant(glyph, False, False, True, False, False, False))
	gs.create(0x1FB04, lambda glyph: generate_sextant(glyph, True, False, True, False, False, False))
	gs.create(0x1FB05, lambda glyph: generate_sextant(glyph, False, True, True, False, False, False))
	gs.create(0x1FB06, lambda glyph: generate_sextant(glyph, True, True, True, False, False, False))
	gs.create(0x1FB07, lambda glyph: generate_sextant(glyph, False, False, False, True, False, False))
	gs.create(0x1FB08, lambda glyph: generate_sextant(glyph, True, False, False, True, False, False))
	gs.create(0x1FB09, lambda glyph: generate_sextant(glyph, False, True, False, True, False, False))
	gs.create(0x1FB0A, lambda glyph: generate_sextant(glyph, True, True, False, True, False, False))
	gs.create(0x1FB0B, lambda glyph: generate_sextant(glyph, False, False, True, True, False, False))
	gs.create(0x1FB0C, lambda glyph: generate_sextant(glyph, True, False, True, True, False, False))
	gs.create(0x1FB0D, lambda glyph: generate_sextant(glyph, False, True, True, True, False, False))
	gs.create(0x1FB0E, lambda glyph: generate_sextant(glyph, True, True, True, True, False, False))
	gs.create(0x1FB0F, lambda glyph: generate_sextant(glyph, False, False, False, False, True, False))
	gs.create(0x1FB10, lambda glyph: generate_sextant(glyph, True, False, False, False, True, False))
	gs.create(0x1FB11, lambda glyph: generate_sextant(glyph, False, True, False, False, True, False))
	gs.create(0x1FB12, lambda glyph: generate_sextant(glyph, True, True, False, False, True, False))
	gs.create(0x1FB13, lambda glyph: generate_sextant(glyph, False, False, True, False, True, False))
	gs.create(0x1FB14, lambda glyph: generate_sextant(glyph, False, True, True, False, True, False))
	gs.create(0x1FB15, lambda glyph: generate_sextant(glyph, True, True, True, False, True, False))
	gs.create(0x1FB16, lambda glyph: generate_sextant(glyph, False, False, False, True, True, False))
	gs.create(0x1FB17, lambda glyph: generate_sextant(glyph, True, False, False, True, True, False))
	gs.create(0x1FB18, lambda glyph: generate_sextant(glyph, False, True, False, True, True, False))
	gs.create(0x1FB19, lambda glyph: generate_sextant(glyph, True, True, False, True, True, False))
	gs.create(0x1FB1A, lambda glyph: generate_sextant(glyph, False, False, True, True, True, False))
	gs.create(0x1FB1B, lambda glyph: generate_sextant(glyph, True, False, True, True, True, False))
	gs.create(0x1FB1C, lambda glyph: generate_sextant(glyph, False, True, True, True, True, False))
	gs.create(0x1FB1D, lambda glyph: generate_sextant(glyph, True, True, True, True, True, False))
	gs.create(0x1FB1E, lambda glyph: generate_sextant(glyph, False, False, False, False, False, True))
	gs.create(0x1FB1F, lambda glyph: generate_sextant(glyph, True, False, False, False, False, True))
	gs.create(0x1FB20, lambda glyph: generate_sextant(glyph, False, True, False, False, False, True))
	gs.create(0x1FB21, lambda glyph: generate_sextant(glyph, True, True, False, False, False, True))
	gs.create(0x1FB22, lambda glyph: generate_sextant(glyph, False, False, True, False, False, True))
	gs.create(0x1FB23, lambda glyph: generate_sextant(glyph, True, False, True, False, False, True))
	gs.create(0x1FB24, lambda glyph: generate_sextant(glyph, False, True, True, False, False, True))
	gs.create(0x1FB25, lambda glyph: generate_sextant(glyph, True, True, True, False, False, True))
	gs.create(0x1FB26, lambda glyph: generate_sextant(glyph, False, False, False, True, False, True))
	gs.create(0x1FB27, lambda glyph: generate_sextant(glyph, True, False, False, True, False, True))
	gs.create(0x1FB28, lambda glyph: generate_sextant(glyph, True, True, False, True, False, True))
	gs.create(0x1FB29, lambda glyph: generate_sextant(glyph, False, False, True, True, False, True))
	gs.create(0x1FB2A, lambda glyph: generate_sextant(glyph, True, False, True, True, False, True))
	gs.create(0x1FB2B, lambda glyph: generate_sextant(glyph, False, True, True, True, False, True))
	gs.create(0x1FB2C, lambda glyph: generate_sextant(glyph, True, True, True, True, False, True))
	gs.create(0x1FB2D, lambda glyph: generate_sextant(glyph, False, False, False, False, True, True))
	gs.create(0x1FB2E, lambda glyph: generate_sextant(glyph, True, False, False, False, True, True))
	gs.create(0x1FB2F, lambda glyph: generate_sextant(glyph, False, True, False, False, True, True))
	gs.create(0x1FB30, lambda glyph: generate_sextant(glyph, True, True, False, False, True, True))
	gs.create(0x1FB31, lambda glyph: generate_sextant(glyph, False, False, True, False, True, True))
	gs.create(0x1FB32, lambda glyph: generate_sextant(glyph, True, False, True, False, True, True))
	gs.create(0x1FB33, lambda glyph: generate_sextant(glyph, False, True, True, False, True, True))
	gs.create(0x1FB34, lambda glyph: generate_sextant(glyph, True, True, True, False, True, True))
	gs.create(0x1FB35, lambda glyph: generate_sextant(glyph, False, False, False, True, True, True))
	gs.create(0x1FB36, lambda glyph: generate_sextant(glyph, True, False, False, True, True, True))
	gs.create(0x1FB37, lambda glyph: generate_sextant(glyph, False, True, False, True, True, True))
	gs.create(0x1FB38, lambda glyph: generate_sextant(glyph, True, True, False, True, True, True))
	gs.create(0x1FB39, lambda glyph: generate_sextant(glyph, False, False, True, True, True, True))
	gs.create(0x1FB3A, lambda glyph: generate_sextant(glyph, True, False, True, True, True, True))
	gs.create(0x1FB3B, lambda glyph: generate_sextant(glyph, False, True, True, True, True, True))
